# Generated by Django 6.0.1 on 2026-01-29 17:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên hiển thị của danh mục', max_length=200, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(help_text='Đường dẫn thân thiện (tự động tạo từ tên)', max_length=200, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh đại diện danh mục (tùy chọn)', null=True, upload_to='categories/%Y/%m/', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, help_text='Mô tả ngắn về danh mục', verbose_name='Mô tả')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị (số nhỏ hiển thị trước)', verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, help_text='Danh mục có hiển thị trên website không', verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('parent', models.ForeignKey(blank=True, help_text='Danh mục cha (để trống nếu là danh mục gốc)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên đầy đủ của sản phẩm', max_length=500, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(help_text='Đường dẫn thân thiện (tự động tạo từ tên)', max_length=500, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, help_text='Mô tả ngắn hiển thị trong danh sách sản phẩm', max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, help_text='Mô tả đầy đủ sản phẩm (hỗ trợ HTML)', verbose_name='Mô tả chi tiết')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Thông số kỹ thuật dạng JSON (RAM, Pin, Màn hình...)', verbose_name='Thông số kỹ thuật')),
                ('price', models.DecimalField(decimal_places=0, help_text='Giá bán (VND)', max_digits=12, verbose_name='Giá bán')),
                ('original_price', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Giá gốc (để hiển thị giảm giá)', max_digits=12, verbose_name='Giá gốc')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Số lượng sản phẩm còn trong kho', verbose_name='Số lượng tồn kho')),
                ('sku', models.CharField(help_text='Mã sản phẩm (SKU) duy nhất', max_length=100, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, help_text='Sản phẩm có hiển thị trên website không', verbose_name='Hoạt động')),
                ('is_featured', models.BooleanField(default=False, help_text='Sản phẩm nổi bật hiển thị trang chủ', verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(help_text='Danh mục sản phẩm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
